env:
  global:
    - CC_TEST_REPORTER_ID=4d2328c4c89052d7577ffa465986ae92f74c6118433aa0b32a874a8552d3f249
language: node_js
node_js:
  - "stable"
addons:
  code_climate:
    repo_token: VG255QoOXDIeiXc2kRWOzdO9pbNAecJwD
cache:
  directories:
    - "node_modules"
before_script:
  - npm install --save-dev coveralls
  - npm install --save-dev istanbul@1.1.0-alpha.1
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run coveralls
after_script:
  - coveralls < ./coverage/lcov.info
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT